name: CI test
run-name: Task CI/CD Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  project_build:
    runs-on: ubuntu-latest
    steps:

      - name: Installing Java 
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'
            
      - name: Java version
        run: "java -version"

      - name: Clone the project 
        uses: actions/checkout@v4

      - name: Show directory 
        run: "pwd ; ls -al"

      - name: Install dependencies 
        run: "mvn complete"

      - name: Build 
        run: "mvn package -DskipTests"

      - name: Run tests
        run: "mvn test"
